ALTER TABLE "Alerta" ADD COLUMN "ruleId" TEXT NOT NULL DEFAULT 'REPORT_RECURRENCE_30D';
ALTER TABLE "Alerta" ADD COLUMN "tipo" TEXT NOT NULL DEFAULT 'reincidencia_reportes';
ALTER TABLE "Alerta" ADD COLUMN "titulo" TEXT NOT NULL DEFAULT 'Reincidencia detectada';
ALTER TABLE "Alerta" ADD COLUMN "resumenCorto" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Alerta" ADD COLUMN "nivelAtencion" TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE "Alerta" ADD COLUMN "confianza" REAL;
ALTER TABLE "Alerta" ADD COLUMN "periodoInicio" DATETIME;
ALTER TABLE "Alerta" ADD COLUMN "periodoFin" DATETIME;
ALTER TABLE "Alerta" ADD COLUMN "evidenciaJson" TEXT;
ALTER TABLE "Alerta" ADD COLUMN "analisisIaJson" TEXT;
ALTER TABLE "Alerta" ADD COLUMN "primerDetectadoEn" DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00';
ALTER TABLE "Alerta" ADD COLUMN "ultimoDetectadoEn" DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00';
ALTER TABLE "Alerta" ADD COLUMN "revisadoEn" DATETIME;
ALTER TABLE "Alerta" ADD COLUMN "revisadoPorId" INTEGER REFERENCES "Usuario"("id") ON DELETE SET NULL;
ALTER TABLE "Alerta" ADD COLUMN "resueltoEn" DATETIME;
ALTER TABLE "Alerta" ADD COLUMN "notaResolucion" TEXT;
ALTER TABLE "Alerta" ADD COLUMN "versionReglas" TEXT NOT NULL DEFAULT '1';
ALTER TABLE "Alerta" ADD COLUMN "versionPrompt" TEXT;
ALTER TABLE "Alerta" ADD COLUMN "analisisGeneradoEn" DATETIME;
ALTER TABLE "Alerta" ADD COLUMN "huellaAnalisis" TEXT;
ALTER TABLE "Alerta" ADD COLUMN "origen" TEXT NOT NULL DEFAULT 'rule';
UPDATE "Alerta" SET "estado" = CASE WHEN "estado" = 'activa' THEN 'new' WHEN "estado" = 'en_seguimiento' THEN 'monitoring' WHEN "estado" = 'resuelta' THEN 'resolved' ELSE "estado" END, "resumenCorto" = CASE WHEN "resumenCorto" = '' THEN COALESCE("notas", "cantidadReportes" || ' reportes relacionados.') ELSE "resumenCorto" END, "primerDetectadoEn" = "creadoEn", "ultimoDetectadoEn" = "actualizadoEn";
CREATE TABLE "AlertaEvidencia" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "alertaId" INTEGER NOT NULL, "reporteId" INTEGER, "tipoEvidencia" TEXT NOT NULL DEFAULT 'reporte', "instantaneaJson" TEXT, "creadoEn" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("alertaId") REFERENCES "Alerta" ("id") ON DELETE CASCADE, FOREIGN KEY ("reporteId") REFERENCES "Reporte" ("id") ON DELETE SET NULL);
CREATE UNIQUE INDEX "AlertaEvidencia_alertaId_tipoEvidencia_reporteId_key" ON "AlertaEvidencia"("alertaId", "tipoEvidencia", "reporteId");
CREATE INDEX "AlertaEvidencia_reporteId_idx" ON "AlertaEvidencia"("reporteId");
CREATE TABLE "AlertaHistorial" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "alertaId" INTEGER NOT NULL, "estadoAnterior" TEXT, "estadoNuevo" TEXT NOT NULL, "motivo" TEXT, "usuarioId" INTEGER, "proceso" TEXT, "creadoEn" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("alertaId") REFERENCES "Alerta" ("id") ON DELETE CASCADE, FOREIGN KEY ("usuarioId") REFERENCES "Usuario" ("id") ON DELETE SET NULL);
CREATE INDEX "Alerta_estudianteId_ruleId_idx" ON "Alerta"("estudianteId", "ruleId");
CREATE INDEX "Alerta_estado_nivelAtencion_actualizadoEn_idx" ON "Alerta"("estado", "nivelAtencion", "actualizadoEn");
CREATE UNIQUE INDEX "Alerta_activa_estudiante_regla_key" ON "Alerta"("estudianteId", "ruleId") WHERE "estado" IN ('new', 'reviewed', 'monitoring');
CREATE INDEX "AlertaHistorial_alertaId_creadoEn_idx" ON "AlertaHistorial"("alertaId", "creadoEn");
INSERT INTO "AlertaHistorial" ("alertaId", "estadoAnterior", "estadoNuevo", "motivo", "proceso") SELECT "id", NULL, "estado", 'Migración al motor de alertas por reglas', 'migration:0002' FROM "Alerta";
DELETE FROM "Alerta" WHERE "notas" LIKE '%[DEMO DASHBOARD]%' OR "titulo" LIKE '%[DEMO DASHBOARD]%';
