ALTER TABLE "Evento" ADD COLUMN "tipo" TEXT NOT NULL DEFAULT 'Evento';
ALTER TABLE "Evento" ADD COLUMN "color" TEXT NOT NULL DEFAULT 'azul';
ALTER TABLE "Evento" ADD COLUMN "todoElDia" INTEGER NOT NULL DEFAULT 0;
